CREATE TABLE Fornecedor (
    Id int IDENTITY(1,1) Primary key,
    Nome Varchar(100),
    Email Varchar(100),
    Documento Varchar(20),
    PessoaFisica Bit,
    RG Varchar(20),
    Nascimento Date
);

CREATE TABLE Empresa (
    Id int IDENTITY(1,1) Primary key,
    CNPJ Varchar(20),
    NomeFantasia Varchar(100),
    UF Varchar(2)
);

CREATE TABLE UnidadeFederativa (
    UF Varchar(2) Primary key,
    Nome Varchar(50) NOT null
);

CREATE TABLE FornecedorEmpresa (
    Id int IDENTITY(1,1) Primary key,
    IdEmpresa int,
    IdFornecedor int
);

ALTER TABLE FornecedorEmpresa
ADD CONSTRAINT FK_FORNECEDOR FOREIGN KEY (IdFornecedor) REFERENCES  Fornecedor(Id);

ALTER TABLE FornecedorEmpresa
ADD CONSTRAINT FK_EMPRESA FOREIGN KEY (IdEmpresa) REFERENCES  Empresa(Id);

ALTER TABLE Empresa
ADD CONSTRAINT FK_EMPRESA_UF FOREIGN KEY (UF) REFERENCES  UnidadeFederativa(UF);

ALTER TABLE FornecedorEmpresa
ADD CONSTRAINT UQ_FE UNIQUE(IdEmpresa, IdFornecedor);


ALTER TABLE Fornecedor
ADD CONSTRAINT UQ_FORNECEDOR_DOC UNIQUE(Documento);

ALTER TABLE Fornecedor
ADD CONSTRAINT UQ_FORNECEDOR_RG UNIQUE(RG);

ALTER TABLE Empresa
ADD CONSTRAINT UQ_EMPRESA_RG UNIQUE(CNPJ);

INSERT INTO UNIDADEFEDERATIVA (NOME, UF) VALUES ('Rondônia', 'RO');
INSERT INTO UNIDADEFEDERATIVA (NOME, UF) VALUES ('Acre', 'AC');
INSERT INTO UNIDADEFEDERATIVA (NOME, UF) VALUES ('Amazonas', 'AM');
INSERT INTO UNIDADEFEDERATIVA (NOME, UF) VALUES ('Roraima', 'RR');
INSERT INTO UNIDADEFEDERATIVA (NOME, UF) VALUES ('Pará', 'PA');
INSERT INTO UNIDADEFEDERATIVA (NOME, UF) VALUES ('Amapá', 'AP');
INSERT INTO UNIDADEFEDERATIVA (NOME, UF) VALUES ('Tocantins', 'TO');
INSERT INTO UNIDADEFEDERATIVA (NOME, UF) VALUES ('Maranhão', 'MA');
INSERT INTO UNIDADEFEDERATIVA (NOME, UF) VALUES ('Piauí', 'PI');
INSERT INTO UNIDADEFEDERATIVA (NOME, UF) VALUES ('Ceará', 'CE');
INSERT INTO UNIDADEFEDERATIVA (NOME, UF) VALUES ('Rio Grande do Norte', 'RN');
INSERT INTO UNIDADEFEDERATIVA (NOME, UF) VALUES ('Paraíba', 'PB');
INSERT INTO UNIDADEFEDERATIVA (NOME, UF) VALUES ('Pernambuco', 'PE');
INSERT INTO UNIDADEFEDERATIVA (NOME, UF) VALUES ('Alagoas', 'AL');
INSERT INTO UNIDADEFEDERATIVA (NOME, UF) VALUES ('Sergipe', 'SE');
INSERT INTO UNIDADEFEDERATIVA (NOME, UF) VALUES ('Bahia', 'BA');
INSERT INTO UNIDADEFEDERATIVA (NOME, UF) VALUES ('Minas Gerais', 'MG');
INSERT INTO UNIDADEFEDERATIVA (NOME, UF) VALUES ('Espírito Santo', 'ES');
INSERT INTO UNIDADEFEDERATIVA (NOME, UF) VALUES ('Rio de Janeiro', 'RJ');
INSERT INTO UNIDADEFEDERATIVA (NOME, UF) VALUES ('São Paulo', 'SP');
INSERT INTO UNIDADEFEDERATIVA (NOME, UF) VALUES ('Paraná', 'PR');
INSERT INTO UNIDADEFEDERATIVA (NOME, UF) VALUES ('Santa Catarina', 'SC');
INSERT INTO UNIDADEFEDERATIVA (NOME, UF) VALUES ('Rio Grande do Sul', 'RS');
INSERT INTO UNIDADEFEDERATIVA (NOME, UF) VALUES ('Mato Grosso do Sul', 'MS');
INSERT INTO UNIDADEFEDERATIVA (NOME, UF) VALUES ('Mato Grosso', 'MT');
INSERT INTO UNIDADEFEDERATIVA (NOME, UF) VALUES ('Goiás', 'GO');
INSERT INTO UNIDADEFEDERATIVA (NOME, UF) VALUES ('Distrito Federal', 'DF');